packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': 1.4.7
  '@convex-dev/better-auth': ^0.10.0
  better-auth: 1.4.7
  convex: ^1.29.3
  dotenv: ^17.2.2
  typescript: ^5
  zod: ^4.1.13

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - msw
  - sharp
  - unrs-resolver
